services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: netsendo-v2-app
    container_name: netsendo-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
      - "5173:5173"
    networks:
      - netsendo-network

  webserver:
    image: nginx:alpine
    container_name: netsendo-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netsendo-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: netsendo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-netsendo}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-netsendo}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - netsendo-network
    ports:
      - "33006:3306"

  redis:
    image: redis:alpine
    container_name: netsendo-redis
    restart: unless-stopped
    networks:
      - netsendo-network
    volumes:
      - redisdata:/data

  mailpit:
    image: axllent/mailpit
    container_name: netsendo-mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - netsendo-network

networks:
  netsendo-network:
    driver: bridge

volumes:
  dbdata:
  redisdata:
